<?php
/**
 * Dependency manifest for the Snap Cart block editor script.
 *
 * The block script is hand-written rather than bundled, so this file declares
 * its dependencies explicitly instead of being generated by a build tool.
 *
 * @package SnapCart
 */

return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-block-editor',
		'wp-components',
		'wp-element',
		'wp-i18n',
	),
	'version'      => '2.1.1',
);
